name: Anchor

on:
  push:
    branches: [ "master", "github-actions" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & get binary from container
      run: cd ./dex && docker build -o out .
    - name: Check existence of binary
      run: ls -al ./out