name: anchor-build
run-name: ${{ github.actor }} is verifying a DEX program.
on: 
  push:
    branches:
      - 'master'
      - 'github-actions'
jobs:
  build-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - run: pwd 
      - run: ls -al
      - run: printenv
